### ISSUE TITLE
Multiple choice for the explore content

### ISSUE THREAD

**Issue by defjosiah** [defjosiah/dowling-hart#11]

**Comment by defjosiah** [comment]
Starting on this one now

**Comment by wcaleb** [comment]
One thought I had about this was to make the tip a blockquote in the Markdown and then use the block quote to control hide/show in the template. 

The more human readable we can keep the Markdown, the easier it will be for later teaches or people to modify. Though we have already departed from that principle somewhat with figures ...

Also, if you want to use CSS instead of JS to hide/show the tip and a "correct" or "try again" message, you might have a look at the approach I'm taking on issue #13. 

Further explanation here:

http://tympanus.net/codrops/2012/12/17/css-click-events/

**Comment by defjosiah** [comment]
Nice, I'll definitely check that one out!
